### PR TITLE
Add reusable card component

### PR DESCRIPTION
**Pull request by chilupa**
As per [Issue #21](https://github.com/KaranSinghBisht/Space-Frontend/issues/21), added reusable card component

### CODE REVIEW

**Comment by KaranSinghBisht** [comment]
Can you add a preview of the card component

**Comment by chilupa** [comment]
Here's the preview of `Card` component @KaranSinghBisht 

preview

On Home page, it looks like this.

home-page-preview

**Comment by inovux** [comment]
Not in line with the current code base, since we are not using material UI :O

**Comment by chilupa** [comment]
I see 😄   So, it would be just plain CSS then? @inovux

**Comment by inovux** [comment]
> I see 😄 So, it would be just plain CSS then? @inovux

Nope I actually abstracted away the fontawesome component in our own Icon component. So you just have to add the specific icon you want to add to that component, and the properties you need: maybe a color property because your using white and a onClick property.

**Comment by KaranSinghBisht** [comment]
It's not an issue if it's not inline with the current code, anyone is free to use any library they want to use 

Btw great work 👍

**Comment by chilupa** [comment]
> It's not an issue if it's not inline with the current code, anyone is free to use any library they want to use
> 
> Btw great work 👍

Thank you @KaranSinghBisht Appreciate it. Used `Material-UI` as it minimizes the lines of code and is easy to reuse its responsive components. I hope my PR is good then? Let me know if I have to make any changes.

**Pull request closed without merging**
