### PR TITLE
 Contributing.md

### PR DESCRIPTION
**Pull request by ravigautamcs**
Solved issue

### CODE REVIEW

**Comment by KaranSinghBisht** [comment]
Just Created a file contributing.md ....

**Comment by ravigautamcs** [comment]
Sir please don't mark it as invalid

**Comment by inovux** [comment]
@ravigautamcs You didn't do anything? What do you expect :D

**Comment by ravigautamcs** [comment]
I am a new beginner to this github and in issues it is written that create a file contributing.md so i have created.
But till now i have completed my four valid pull request.
Please don't mark it with invalid please it will make me out from the hacktoberfest.
Please
Please
Please
Please 🙏🙏🙏🙏

**Comment by ravigautamcs** [comment]
You can see my github profile i am new. And even i am all doing this coding from my smartphone because i can't afford a laptop😟.
Please sir please

**Comment by ravigautamcs** [comment]
Please remove the invalid label

**Comment by KaranSinghBisht** [comment]
@ravigautamcs 
You can contribute really easily to README.md by
* Cloning the repo 
* ` npm install`
* ` npm start`
Add then add a few pictures of the site with the current date
And also add how to contribute to the repo ( Like I told you, 1. npm install etc

This is a very easy task and I assure you if you can contribute even this much I'll check the pr and might even merge it :smile: !

**Comment by ravigautamcs** [comment]
Thankyou very much. I will do it for sure

**Pull request closed without merging**
